### PR TITLE
Implements JUnit tests for MenuService class

### PR DESCRIPTION
**Pull request by BartoliniAndBorderCollies**
#### Issue
https://trello.com/c/Plzw2aM1

### Description
This branch covers 100% `MenuService` class with JUnit tests.

### Motivation
Another bunch of tests - a must be for every public application which is going to be released.

### Changes introduced by this pull request

- add test methods to cover 100% `MenuService` class

### Testing

- [x] all tests are operational and working fine

### CODE REVIEW

**Comment by JasinskiSz** [comment]
This test class doesn't cover 100% of the tested class as you're stating.
image
You didn't include one case. Do you know which one?

**Comment by BartoliniAndBorderCollies** [comment]
I guess its a private method which you mentioned before it was not needed to cover:
image

**Comment by JasinskiSz** [comment]
Nope, that's not it. By looking at these green bars (just to the right of the line numbers) on your screenshot you can see that your code went "through" those. Meaning it's covered. If there is a red bar instead of green, program didn't reach that place - it is not covered by tests.
So issue is not with this private method. And by saying that we don't test private methods doesn't mean we don't want to get inside of them. That's different as we will get into our private methods when testing public ones.

**Comment by BartoliniAndBorderCollies** [comment]
OK method added! thanks for watching it! ready for re review

**Review by JasinskiSz — APPROVED** [review]
Ok then! Looks like done, good job!

**Pull request merged**
